const SongConstants = {
	SONGS_RECEIVED: "SONGS_RECEIVED",
	SONG_RECEIVED: "SONG_RECEIVED",
	// ANNOTATIONS_RECEIVED: "ANNOTATIONS_RECEIVED",
	ANNOTATION_RECEIVED: "ANNOTATION_RECEIVED"
};

module.exports = SongConstants;
