const SongConstants = {
	SONGS_RECEIVED: "SONGS_RECEIVED",
	SONG_RECEIVED: "SONG_RECEIVED",
	ANNOTATION_RECEIVED: "ANNOTATION_RECEIVED",
	SONG_COMMENT_RECEIVED: "SONG_COMMENT_RECEIVED",
	ANNOTATION_COMMENT_RECEIVED: "ANNOTATION_COMMENT_RECEIVED"
};

module.exports = SongConstants;
