const SongConstants = {
	SONGS_RECEIVED: "SONGS_RECEIVED",
	SONG_RECEIVED: "SONG_RECEIVED",
	SONG_COMMENT_RECEIVED: "SONG_COMMENT_RECEIVED",
	ANNOTATION_COMMENT_RECEIVED: "ANNOTATION_COMMENT_RECEIVED",
	SONGS_SEARCHED: "SONGS_SEARCHED"
};

module.exports = SongConstants;
